# Generated by Django 3.1.6 on 2021-02-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='studentuser',
            old_name='MobileNo',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
